const menu = [
    {
      id: 1,
      title: "Coolor",
      category: "color",
      link: "http://coolors.co/",
      img: "./src/asset-01.png",
      desc: `Generate or browse beautiful color combinations for your designs. `,
    },
    {
      id: 2,
      title: "CSS Layout",
      category: "template",
      link: "https://csslayout.io",
      img: "./src/asset-02.png",
      desc: `Popular Layouts & patterns made with CSS. Zero Dependencies. No Frameworks. No CSS Hacks. Real Use Cases. Good Practices.`,
    },
    {
      id: 3,
      title: "Code Pen",
      category: "editor",
      link: 'https://codepen.io',
      img: "./src/asset-03.jpg",
      desc: `Code Pen is an online community for testing and showcasing user-created HTML, CSS and JavaScript code snippets.`,
    }
    ,
    {
      id: 4,
      title: "Laws of UX",
      category: "documentation",
      link: 'https://lawsofux.com',
      img: "./src/asset-04.jpg",
      desc: `Laws of UX is a collection of best practices that designers can consider when building user interfaces.`,
    }
    ,
    {
      id: 5,
      title: "Code Academy",
      category: "cheatsheet",
      link: 'https://codepen.io',
      img: "./src/asset-05.jpg",
      desc: `all cheatsheet (CSS, Javascript, HTML)`,
    }
    ,
    {
      id: 6,
      title: "Javascript Info",
      category: "cheatsheet",
      link: 'https://javascript.info',
      img: "./src/asset-06.jpg",
      desc: `cheatsheet documentation javascript`,
    }
    ,
    {
      id: 7,
      title: "CSS Tricks",
      category: "cheatsheet",
      link: 'https://css-tricks.com',
      img: "./src/asset-07.jpg",
      desc: `Daily articles about CSS, HTML, JavaScript, and all things related to web design and development.`,
    },
    {
      id: 8,
      title: "30 Seconds Of Code",
      category: "cheatsheet",
      link: 'https://www.30secondsofcode.org',
      img: "./src/asset-08.jpg",
      desc: `CBrowse 1043 short code snippets for all your development needs on 30 seconds of code.`,
    },
    {
      id: 9,
      title: "Code to Go",
      category: "cheatsheet",
      link: 'https://codetogo.io',
      img: "./src/asset-09.jpg",
      desc: `Javascript code to go: Find updated snippets for common JavaScript use cases.`,
    },
    {
      id: 10,
      title: "W3 School",
      category: "cheatsheet",
      link: 'https://www.w3schools.com',
      img: "./src/asset-10.jpg",
      desc: `Free course, cheatsheet, practice.`,
    },
    {
      id: 11,
      title: "1 Loc Dev",
      category: "cheatsheet",
      link: 'https://1loc.dev',
      img: "./src/asset-11.jpg",
      desc: `Favorite JavaScript utilities in single line of code.`,
    },
    {
      id: 12,
      title: "Geeks for Geeks",
      category: "cheatsheet",
      link: 'https://www.geeksforgeeks.org',
      img: "./src/asset-12.jpg",
      desc: `A Computer Science portal for geeks. It contains well written, well thought and well explained computer science and programming articles. (course, free)`,
    },
    {
      id: 13,
      title: "Animista",
      category: "cheatsheet",
      link: 'https://animista.net',
      img: "./src/asset-13.jpg",
      desc: `Animista is a CSS animation library and a place where you can play with a collection of ready-made CSS animations and download only those you will use.`,
    },
    {
      id: 14,
      title: "Elemental UI",
      category: "cheatsheet",
      link: 'http://elemental-ui.com',
      img: "./src/asset-14.jpg",
      desc: `Elemental UI is the cornerstone of Thinkmill's development suite, made by people who share a passion for HTML, CSS and JavaScript.`,
    },
    {
      id: 15,
      title: "Evergreen",
      category: "cheatsheet",
      link: 'http://elemental-ui.com',
      img: "./src/asset-15.jpg",
      desc: `Evergreen, A Design System for the Web. Evergreen is a React UI Framework for. Build Status. Works out of the box. Evergreen. (React, CSS)`,
    },
    {
      id: 16,
      title: "HTTP CAT",
      category: "cheatsheet",
      link: 'https://http.cat',
      img: "./src/asset-16.jpg",
      desc: `An API for the awesome HTTP Cats! Use it in your website to show funny error messages.`,
    },
    {
      id: 17,
      title: "iHateRegex",
      category: "cheatsheet",
      link: 'https://ihateregex.io',
      img: "./src/asset-17.jpg",
      desc: `i Hate Regex is a regex cheat sheet that also explains the commonly used expressions so that you understand it.`,
    },
    {
      id: 18,
      title: "CSS Unfold",
      category: "cheatsheet",
      link: 'https://codepen.io',
      img: "./src/asset-18.jpg",
      desc: `cheatsheet css unfold.<br>(CSS,Fun, Game)`,
    },
    {
      id: 19,
      title: "Big O Cheat Sheat",
      category: "cheatsheet",
      link: 'https://bigocheatsheet.io',
      img: "./src/asset-19.jpg",
      desc: `Big-O Cheat Sheet for Some Data Structures and Algorithms.`,
    },
    {
      id: 20,
      title: "I Love Coding",
      category: "cheatsheet",
      link: 'https://ilovecoding.org/blog/htmlcss-cheatsheet',
      img: "./src/asset-20.jpg",
      desc: `Cheatsheet css html<br> (course)`,
    },
    {
      id: 21,
      title: "Devhints",
      category: "cheatsheet",
      link: 'https://devhints.io',
      img: "./src/asset-21.jpg",
      desc: `Cheatsheet`,
    },
    {
      id: 22,
      title: "DevDocs",
      category: "cheatsheet",
      link: 'https://devdocs.io',
      img: "./src/asset-22.jpg",
      desc: `DevDocs combines multiple API documentations in a fast, organized, and searchable interface. <br> (documentation/cheatsheet)`,
    },
    {
      id: 23,
      title: "CSS References",
      category: "cheatsheet",
      link: 'https://cssreference.io',
      img: "./src/asset-23.jpg",
      desc: `A free visual guide to CSS`,
    },
    {
      id: 24,
      title: "sync.com",
      category: "cloud",
      link: 'https://www.sync.com/free-cloud-storage/',
      img: "./src/asset-24.jpg",
      desc: `A safe space for the world to collaborate · Our cloud syncing platform and apps bring people together to do truly incredible things. <br> (Cloud, Hosting)`,
    },
    {
      id: 25,
      title: "iceDrive",
      category: "cloud",
      link: 'https://icedrive.net',
      img: "./src/asset-25.jpg",
      desc: `cloud storage with Icedrive<br>(Hosting, Cloud, Free)`,
    },
    {
      id: 26,
      title: "Picular",
      category: "color",
      link: 'https://picular.co',
      img: "./src/asset-26.jpg",
      desc: `Picular is a rocket fast primary color generator using Google's image search. If you ever needed the perfect yellow hex code from a banana, this is the tool.<br> (Color)`,
    },
    {
      id: 27,
      title: "2 Colors colorion",
      category: "color",
      link: 'https://2colors.colorion.co',
      img: "./src/asset-27.jpg",
      desc: `two combination color`,
    },
    {
      id: 28,
      title: "Pigment Color",
      category: "color",
      link: 'https://pigment.shapefactory.co',
      img: "./src/asset-28.jpg",
      desc: `A unique way to generate fresh and vibrant colors based on lighting and pigment, instead of math. Find a beautiful, free color palette`,
    },
    {
      id: 29,
      title: "Palx Color",
      category: "color",
      link: 'https://palx.jxnblk.com',
      img: "./src/asset-29.jpg",
      desc: `Color palette combination contrast tester. Tweet. Take a set color palette and get contrast values for every possible combination`,
    },
    {
      id: 30,
      title: "Colorable",
      category: "color",
      link: 'https://colorable.jxnblk.com/75de73/871e89',
      img: "./src/asset-30.jpg",
      desc: `Color palette combination contrast tester. Tweet. Take a set color palette and get contrast values for every possible combination`,
    },
    {
      id: 31,
      title: "Colorbox",
      category: "color",
      link: 'https://colorbox.io',
      img: "./src/asset-31.jpg",
      desc: `Color Generator`,
    },
    {
      id: 32,
      title: "Paletton",
      category: "color",
      link: 'https://paletton.com/',
      img: "./src/asset-32.jpg",
      desc: `Paletton is not just a professional's tool, it was designed to help all sorts of color projects, from professional work to your kids school projects.`,
    },
    {
      id: 33,
      title: "Adobe Color",
      category: "color",
      link: 'https://color.adobe.com',
      img: "./src/asset-33.jpg",
      desc: `Create color palettes with the color wheel or image, browse thousands of color combinations from the Adobe Color community.`,
    },
    {
      id: 34,
      title: "Khroma",
      category: "color",
      link: 'http://khroma.co',
      img: "./src/asset-34.jpg",
      desc: `Khroma is the fastest way to discover, search, and save color combos and palettes you'll love.`,
    },
    {
      id: 35,
      title: "Color Mind",
      category: "color",
      link: 'http://colormind.io',
      img: "./src/asset-35.jpg",
      desc: `Colormind is a color scheme generator that uses deep learning. It can learn color styles from photographs, movies, and popular art.`,
    },
    {
      id: 36,
      title: "Color Hunt",
      category: "color",
      link: 'https://colorhunt.co',
      img: "./src/asset-36.jpg",
      desc: `The Hunter is a filter colorimeter which separates the components of reflected color into a three dimensional color scale.<br>(Color)`,
    },
    {
      id: 37,
      title: "Coursera",
      category: "course",
      link: 'https://www.coursera.org',
      img: "./src/asset-37.jpg",
      desc: `Coursera is a global online learning platform that offers anyone, anywhere, access to online courses and degrees from leading universities and companies.`,
    },
    {
      id: 38,
      title: "Indonesia X",
      category: "course",
      link: 'https://www.indonesiax.co.id',
      img: "./src/asset-38.jpg",
      desc: `IndonesiaX adalah platform online pendidikan yang menawarkan kursus-kursus online (Massive Open Online Courses) dari universitas`,
    },
    {
      id: 39,
      title: "eDx",
      category: "course",
      link: 'https://www.edx.org',
      img: "./src/asset-39.jpg",
      desc: `Access 2000 free online courses from 140 leading institutions worldwide. Gain new skills and earn a certificate of completion.`,
    },
    {
      id: 40,
      title: "Google Digital Garage",
      category: "course",
      link: 'learndigital.withgoogle.com',
      img: "./src/asset-40.jpg",
      desc: `Learn digital skills for free at your own pace, with personalised training designed to help you develop your career, market your business, and more.`,
    },
    {
      id: 41,
      title: "Google Skill Shop",
      category: "course",
      link: 'https://skillshop.withgoogle.com',
      img: "./src/asset-41.jpg",
      desc: `Access free online training to develop skills for Google workplace tools. Learn at your own pace and get Google product certified along the way.`,
    },
    {
      id: 42,
      title: "dqLab",
      category: "course",
      link: 'https://dqlab.id',
      img: "./src/asset-42.jpg",
      desc: `Perusahaan konsultan bisnis serta penyimpanan (warehouse) data yang berdirisejak 2005 memberikan solusi data yang berhasil di adopsi perusahaan ternama.`,
    },
    {
      id: 43,
      title: "The Odin Project",
      category: "course",
      link: 'https://www.theodinproject.com',
      img: "./src/asset-43.jpg",
      desc: `The Odin Project empowers aspiring web developers to learn together. <br>(Course/Project/Practice)`,
    },
    {
      id: 44,
      title: "Learn Javascript",
      category: "course",
      link: 'https://learnjavascript.online',
      img: "./src/asset-44.jpg",
      desc: `Learn in an interactive environment. Read short lessons, take notes, and complete challenges directly in your browser. <br> (Course/Practice/Project)`,
    },
    {
      id: 45,
      title: "Great Learning",
      category: "course",
      link: 'https://www.mygreatlearning.com/',
      img: "./src/asset-45.jpg",
      desc: `Learn the in-demand skills to advance your career in AI, ML, data science, digital marketing, cloud, software engg & more. <br> (Course/Practice/Project)`,
    },
    {
      id: 46,
      title: "LingoHut",
      category: "course",
      link: 'https://www.lingohut.com/id',
      img: "./src/asset-46.jpg",
      desc: `Course language  <br> (Course/Practice/Project)`,
    },
    {
      id: 47,
      title: "Hari Senin",
      category: "course",
      link: 'https://www.harisenin.com',
      img: "./src/asset-47.jpg",
      desc: `Temukan mentor dan jasa profesional yang tepat untuk bisnismu dengan sekali klik, kapan saja dan dimana saja. <br> (Course/Practice/Project)`,
    },
    {
      id: 48,
      title: "Kumpulan Link",
      category: "course",
      link: 'https://diskusi.tech/hadestech/kumpulan-link-untuk-belajar-ofe',
      img: "./src/asset-48.jpg",
      desc: `Learning-List Informasi Update Full Source Referensi Untuk Belajar Apapun. <br> (Course/Practice/Project)`,
    },
    {
      id: 49,
      title: "Free for Dev",
      category: "documentation",
      link: 'https://free-for.dev/#/?id=font',
      img: "./src/asset-49.jpg",
      desc: `Free for Dev.`,
    },
    {
      id: 50,
      title: "Public APIs",
      category: "documentation",
      link: 'https://public-apis.io',
      img: "./src/asset-50.jpg",
      desc: `A collective list of more than 1000 Free Public and Open REST APIs for developers like movie APIs, Anime APIs, weather APIs, music APIs, games and comics. <br> (documentation/cheatsheet)`,
    },
    {
      id: 51,
      title: "UI Design",
      category: "documentation",
      link: 'https://www.dwinawan.com/learn#',
      img: "./src/asset-51.jpg",
      desc: `UIUX Basic Principal.`,
    },
    {
      id: 52,
      title: "CodeSandbox",
      category: "editor",
      link: 'https://codesandbox.io',
      img: "./src/asset-52.jpg",
      desc: `CodeSandbox is an online code editor and prototyping tool that makes creating and sharing web apps faster.`,
    },
    {
      id: 53,
      title: "ide onelang",
      category: "editor",
      link: 'https://ide.onelang.io',
      img: "./src/asset-53.jpg",
      desc: `Hey there! If this is the first time you are using Onelang WebIDE then I recommend watching. <br>(cheatsheet/convert)`,
    },
    {
      id: 54,
      title: "Font Squirrel",
      category: "fonts",
      link: 'https://www.fontsquirrel.com',
      img: "./src/asset-54.jpg",
      desc: `Font Squirrel scours the internet for high quality, legitimately free fonts . Download thousands of completely legal, high quality, free fonts.`,
    },
    {
      id: 55,
      title: "Awwwards Font",
      category: "fonts",
      link: 'https://www.awwwards.com/awwwards/collections/free-fonts/',
      img: "./src/asset-55.jpg",
      desc: `Free Fonts form Awwwards.`,
    },
    {
      id: 56,
      title: "Cufon Fonts",
      category: "fonts",
      link: 'https://www.cufonfonts.comhttps://www.cufonfonts.com',
      img: "./src/asset-56.jpg",
      desc: `The world's most comprehensive Webfonts supported free font archive. For designers and developers.`,
    },
    {
      id: 57,
      title: "Dafont",
      category: "fonts",
      link: 'https://www.dafont.com',
      img: "./src/asset-57.jpg",
      desc: `Archive of freely downloadable fonts. Browse by alphabetical listing, by style, by author or by popularity.`,
    },
    {
      id: 58,
      title: "Font Share",
      category: "fonts",
      link: 'https://www.fontshare.com',
      img: "./src/asset-58.jpg",
      desc: `Fontshare is a free fonts service from ITF, making quality fonts accessible to all.`,
    },
    {
      id: 59,
      title: "Google Fonts",
      category: "fonts",
      link: 'https://fonts.google.com',
      img: "./src/asset-59.jpg",
      desc: `Making the web more beautiful, fast, and open through great typography.<br>(Free/Fonts)`,
    },
    {
      id: 60,
      title: "Project id",
      category: "freelance",
      link: 'https://projects.co.id',
      img: "./src/asset-60.jpg",
      desc: `Projects.co.id adalah website untuk mencari jasa freelancer dan transaksi produk digital dengan sistem kerja remote`,
    },
    {
      id: 61,
      title: "Daily Remote",
      category: "freelance",
      link: 'https://dailyremote.com',
      img: "./src/asset-61.jpg",
      desc: `Find and apply for top remote jobs in Software Development, Design, Support, Sales, Writing, Product, and Others. Start telecommuting & working from home. <br>(Freelance/Jobs)`,
    },
    {
      id: 62,
      title: "Vue Jobs",
      category: "freelance",
      link: 'https://vuejobs.com',
      img: "./src/asset-62.jpg",
      desc: `Vue.js jobs is the best place to hire or get hired as Vue.js developer. Find Vue.js talent and reach to thousands of developers.`,
    },
    {
      id: 63,
      title: "WeWork Remotly",
      category: "freelance",
      link: 'https://weworkremotely.com',
      img: "./src/asset-63.jpg",
      desc: `We Work Remotely is the largest remote work community in the world.`,
    },
    {
      id: 64,
      title: "Remote OK",
      category: "freelance",
      link: 'https://remoteok.io',
      img: "./src/asset-64.jpg",
      desc: `RemoteOK is an online job posting site for companies that need to fill remote positions.`,
    },
    {
      id: 65,
      title: "Dynamite Jobs",
      category: "freelance",
      link: 'https://dynamitejobs.com/how-to-find-remote-jobs',
      img: "./src/asset-65.jpg",
      desc: `Dynamite Jobs is the easiest place to find and post great remote jobs. We vet all listings. Let's work together!`,
    },
    {
      id: 66,
      title: "JS Remotly",
      category: "freelance",
      link: 'https://jsremotely.com',
      img: "./src/asset-66.jpg",
      desc: `Welcome to JS Remotely, the job board with all JavaScript remote jobs in the world.`,
    },
    {
      id: 67,
      title: "JS Dev Jobs",
      category: "freelance",
      link: 'https://javascriptjob.xyz',
      img: "./src/asset-67.jpg",
      desc: `Find specific JavaScript Developer Jobs, including Remote Jobs. You are looking for JavaScript Developers? Submit your position for free.`,
    },
    {
      id: 68,
      title: "Fiverr",
      category: "freelance",
      link: 'http://fiverr.com',
      img: "./src/asset-68.jpg",
      desc: `Fiverr's mission is to change how the world works together.`,
    },
    {
      id: 69,
      title: "UpWork",
      category: "freelance",
      link: 'https://www.upwork.com',
      img: "./src/asset-69.jpg",
      desc: `Upwork connects businesses with freelancers, independent talent, and agencies around the globe.`,
    },
    {
      id: 70,
      title: "TrueLancer",
      category: "freelance",
      link: 'https://www.truelancer.com',
      img: "./src/asset-70.jpg",
      desc: `Truelancer holds the funds you pay to the Freelancers in Safe Deposit until the work is completed & approved by you.`,
    },
    {
      id: 71,
      title: "People per Hours",
      category: "freelance",
      link: 'https://www.peopleperhour.com',
      img: "./src/asset-71.jpg",
      desc: `Get any project done on PeoplePerHour - the #1 freelancing community. Post a project for free to find professional freelancers`,
    },
    {
      id: 72,
      title: "Guru",
      category: "freelance",
      link: 'https://www.guru.com',
      img: "./src/asset-72.jpg",
      desc: `Guru is one of the best freelance websites to find & hire Freelancers online and get work done.`,
    },
    {
      id: 73,
      title: "Radiooooo",
      category: "fun",
      link: 'https://radiooooo.com',
      img: "./src/asset-73.jpg",
      desc: `Radio play arround the world`,
    },
    {
      id: 74,
      title: "Muscle Wiki",
      category: "fun",
      link: 'https://musclewiki.com',
      img: "./src/asset-74.jpg",
      desc: `muscle ai.`,
    },
    {
      id: 75,
      title: "My 90s TV",
      category: "fun",
      link: 'https://www.my90stv.com',
      img: "./src/asset-75.jpg",
      desc: `Go back to the 1990's via this nostalgic TV simulator and relive the original ads, music videos, movie trailers, shows and more!`,
    },
    {
      id: 76,
      title: "Geo Fs",
      category: "fun",
      link: 'https://www.geo-fs.com',
      img: "./src/asset-76.jpg",
      desc: `GeoFS is a free flight simulator using global satellite images and running in your web browser or as a mobile app.`,
    },
    {
      id: 77,
      title: "Room Style",
      category: "fun",
      link: 'https://roomstyler.com',
      img: "./src/asset-77.jpg",
      desc: `for a free Roomstyler account and start decorating with the 120.000+ items. Anyone can create photorealistic 3D renders of the interiors they have`,
    },
    {
      id: 78,
      title: "Play Emulator",
      category: "fun",
      link: 'http://playemulator.com',
      img: "./src/asset-78.jpg",
      desc: `Play emulator games on your PC, tablets, and mobile. PlayEmulator is a convenient way to play old games you used to own that got lost over time.`,
    },
    {
      id: 79,
      title: "Emu OS",
      category: "fun",
      link: 'https://emupedia.net/beta/emuos/',
      img: "./src/asset-79.jpg",
      desc: `The purpose of Emupedia is to serve as a nonprofit meta-resource, hub and community for those interested mainly in video game preservation.`,
    },
    {
      id: 80,
      title: "Bouncing DVD",
      category: "fun",
      link: 'https://www.bouncingdvdlogo.com',
      img: "./src/asset-80.jpg",
      desc: `Bouncing DVD display.`,
    },
    {
      id: 81,
      title: "Neal Fun",
      category: "fun",
      link: 'https://neal.fun',
      img: "./src/asset-81.jpg",
      desc: `Fun Knowledge`,
    },
    {
      id: 82,
      title: "Smash the Wall",
      category: "fun",
      link: 'https://smashthewalls.com',
      img: "./src/asset-82.jpg",
      desc: `smash the wall.`,
    },
    {
      id: 83,
      title: "Hold The Pointer",
      category: "fun",
      link: 'https://pointerpointer.com',
      img: "./src/asset-83.jpg",
      desc: `holdstill the pointer`,
    },
    {
      id: 84,
      title: "Unsolved Riddle",
      category: "fun",
      link: 'https://www.ocf.berkeley.edu/~wwu/riddles/easy.shtml',
      img: "./src/asset-84.jpg",
      desc: `who does love riddles.`,
    },
    {
      id: 85,
      title: "Bezier Game",
      category: "practice",
      link: 'https://bezier.method.ac',
      img: "./src/asset-85.jpg",
      desc: `Play game to improve your pen tool skill.`,
    },
    {
      id: 86,
      title: "Nitro Type",
      category: "practice",
      link: 'https://www.nitrotype.com',
      img: "./src/asset-86.jpg",
      desc: `Game to improve your typing skill.`,
    },
    {
      id: 87,
      title: "Boolean Game",
      category: "practice",
      link: 'https://booleangame.com',
      img: "./src/asset-87.jpg",
      desc: `Boolean Game is the best way to learn and practice boolean operations using colors and numbers.`,
    },
    {
      id: 88,
      title: "Coding Game",
      category: "practice",
      link: 'https://www.codingame.com',
      img: "./src/asset-88.jpg",
      desc: `Improve your coding skill with playing game.`,
    },
    {
      id: 89,
      title: "Code Combat",
      category: "practice",
      link: 'https://codecombat.com',
      img: "./src/asset-89.jpg",
      desc: `CodeCombat is an HTML5 role-playing game (RPG) that teaches you fundamental programming concepts. CodeCombat supports 5 programming languages`,
    },
    {
      id: 90,
      title: "Code Wars",
      category: "practice",
      link: 'https://www.codewars.com',
      img: "./src/asset-90.jpg",
      desc: `Codewars is where developers achieve code mastery through challenge. Train on kata in the dojo and reach your highest potential.`,
    },
    {
      id: 91,
      title: "CSS Grid Garden",
      category: "practice",
      link: 'https://cssgridgarden.com',
      img: "./src/asset-91.jpg",
      desc: `Grid Gardening is a simple, systematic and densely planted gardening method that adapts to diverse experience, ability, and climate zones.`,
    },
    {
      id: 92,
      title: "Flexbox Defense",
      category: "practice",
      link: 'http://www.flexboxdefense.com',
      img: "./src/asset-92.jpg",
      desc: `Unlike other tower defense games, you must position your towers using CSS! We'll start with container properties.`,
    },
    {
      id: 93,
      title: "CSS Diner",
      category: "practice",
      link: 'https://flukeout.github.io/#',
      img: "./src/asset-93.jpg",
      desc: `where we feast on css selectors.`,
    },
    {
      id: 94,
      title: "Flexbox Froggy",
      category: "practice",
      link: 'https://flexboxfroggy.com',
      img: "./src/asset-94.jpg",
      desc: `Flexbox Froggy is a game for learning CSS flexbox. Fun way to learn how to format web content.`,
    },
    {
      id: 95,
      title: "CheckIO",
      category: "practice",
      link: 'https://checkio.org',
      img: "./src/asset-95.jpg",
      desc: `Coding games for beginners and advanced programmers where you can improve your coding skills by solving engaging challenges and fun task using Python and TypeScript`,
    },
    {
      id: 96,
      title: "JS Robot",
      category: "practice",
      link: 'https://lab.reaal.me/jsrobot/',
      img: "./src/asset-96.jpg",
      desc: `Learn JavaScript by playing a platform game: Control a robot to collect coins, avoid obstacles and reach the flag at the end of the level.`,
    },
    {
      id: 97,
      title: "music for programming",
      category: "fun",
      link: 'https://musicforprogramming.net/?one',
      img: "./src/asset-97.jpg",
      desc: `music for programming.`,
    },
    {
      id: 98,
      title: "Cruchzilla",
      category: "practice",
      link: 'https://www.crunchzilla.com',
      img: "./src/asset-98.jpg",
      desc: `Crunchzilla offers interactive tutorials that get people excited about programming. Play with code, build, and learn..`,
    },
    {
      id: 99,
      title: "Netlify",
      category: "hosting",
      link: 'https://www.netlify.com',
      img: "./src/asset-99.jpg",
      desc: `Netlify is a web developer platform that multiplies productivity. By unifying the elements of the modern decoupled web.`,
    },
    {
      id: 100,
      title: "Heroku",
      category: "hosting",
      link: 'https://www.heroku.com',
      img: "./src/asset-100.jpg",
      desc: `Heroku is a container-based cloud Platform as a Service (PaaS). Developers use Heroku to deploy, manage, and scale modern apps`,
    },
    {
      id: 101,
      title: "Firebase",
      category: "hosting",
      link: 'https://firebase.google.com',
      img: "./src/asset-101.jpg",
      desc: `Firebase helps you build and run successful apps. Backed by Google, loved by developers.`,
    },
    {
      id: 102,
      title: "000Webhost",
      category: "hosting",
      link: 'http://www.000webhost.com',
      img: "./src/asset-102.jpg",
      desc: `Absolutely free web hosting with cPanel, PHP & MySQL for a stunning blogging start. Get free website hosting together with a free domain name at no cost`,
    },
    {
      id: 103,
      title: "infinity free",
      category: "hosting",
      link: 'https://infinityfree.net',
      img: "./src/asset-103.jpg",
      desc: `Free Unlimited Website Hosting for over 9 years. <br>InfinityFree is completely free, no credit card required, no time limits and no hidden fees.`,
    },
    {
      id: 104,
      title: "Vercel",
      category: "hosting",
      link: 'https://vercel.com',
      img: "./src/asset-104.jpg",
      desc: `Vercel combines the best developer experience with an obsessive focus on end-user performance. Our platform enables frontend teams to do their best work.`,
    },
    {
      id: 105,
      title: "Render",
      category: "hosting",
      link: 'https://render.com/',
      img: "./src/asset-105.jpg",
      desc: `Render is a unified cloud to build and run all your apps and websites with free SSL, global CDN, private networks and auto deploys from Git.`,
    },
    {
      id: 106,
      title: "ngrok",
      category: "hosting",
      link: 'https://ngrok.com/',
      img: "./src/asset-106.jpg",
      desc: `Ngrok exposes local servers behind NATs and firewalls to the public internet over secure tunnels.`,
    },
    {
      id: 107,
      title: "Github Pages",
      category: "hosting",
      link: 'https://pages.github.com',
      img: "./src/asset-107.jpg",
      desc: `Websites for you and your projects, hosted directly from your GitHub repository. Just edit, push, and your changes are live.`,
    },
    {
      id: 108,
      title: "stromkit",
      category: "hosting",
      link: 'https://www.stormkit.io',
      img: "./src/asset-108.jpg",
      desc: `Make building & delivering applications a delightful low-code-like experience`,
    },
    {
      id: 109,
      title: "Surge.sh",
      category: "hosting",
      link: 'https://surge.sh',
      img: "./src/asset-109.jpg",
      desc: `With Surge, you can use your own domain in place of a surge.sh subdomain. This means you’ll be able to publish to your-own-domain.com.`,
    },
    {
      id: 110,
      title: "Feather Icon",
      category: "icon",
      link: 'https://feathericons.com',
      img: "./src/asset-110.jpg",
      desc: `Feather is a collection of simply beautiful open source icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency, and flexibility.`,
    },
    {
      id: 111,
      title: "Icon Shock",
      category: "icon",
      link: 'https://www.iconshock.com',
      img: "./src/asset-111.jpg",
      desc: `free icons and premium icon packs. Flat icons, Material icons, Glyph icons, iOS icons, Font icons, and more design styles`,
    },
    {
      id: 112,
      title: "Use Animation",
      category: "icon",
      link: 'https://useanimations.com',
      img: "./src/asset-112.jpg",
      desc: `Animated icons in Lottie Framework and for immediate implementation to your apps or websites..`,
    },
    {
      id: 113,
      title: "Lottle Files",
      category: "icon",
      link: 'https://lottiefiles.com',
      img: "./src/asset-113.jpg",
      desc: `Lottie is an open source animation file format that's tiny, high quality, interactive, and can be manipulated at runtime.`,
    },
    {
      id: 114,
      title: "Icon Scout",
      category: "icon",
      link: 'https://iconscout.com/',
      img: "./src/asset-114.jpg",
      desc: `We're building the next-generation Design Resource Marketplace which provides creative assets for individuals and businesses with ease using our innovative tools like Plugins and Apps`,
    },
    {
      id: 115,
      title: "Flat Icon",
      category: "icon",
      link: 'https://www.flaticon.com',
      img: "./src/asset-115.jpg",
      desc: `Download Free Vector Icons and Stickers for your projects. Resources made by and for designers`,
    },
    {
      id: 116,
      title: "Fonts Awesome",
      category: "icon",
      link: 'https://fontawesome.com',
      img: "./src/asset-116.jpg",
      desc: `Font Awesome. Get vector icons and social logos on your website with Font Awesome, the web's most popular icon set and toolkit.`,
    },
    {
      id: 117,
      title: "Icons 8",
      category: "icon",
      link: 'https://icons8.com',
      img: "./src/asset-117.jpg",
      desc: `Download design elements for free: icons, photos, vector illustrations, and music for your videos.`,
    },
    {
      id: 118,
      title: "Fontello",
      category: "icon",
      link: 'https://fontello.com',
      img: "./src/asset-118.jpg",
      desc: `Tool to build custom fonts with icons.`,
    },
    {
      id: 119,
      title: "Mono Icon",
      category: "icon",
      link: 'https://icons.mono.company',
      img: "./src/asset-119.jpg",
      desc: `A simple, consistent open-source icon set designed to be used in a wide variety of digital products`,
    },
    {
      id: 120,
      title: "Iconoir",
      category: "icon",
      link: 'https://iconoir.com',
      img: "./src/asset-120.jpg",
      desc: `Iconoir is one of the biggest open source libraries with currently 941 SVG Icons. No premium icons, no email sign-up, no newsletters.`,
    },
    {
      id: 121,
      title: "SVG Repo",
      category: "icon",
      link: 'https://www.svgrepo.com',
      img: "./src/asset-121.jpg",
      desc: `Free Vectors and Icons in SVG format. ✓ Download free mono or multi color vectors for commercial use.`,
    },
    {
      id: 122,
      title: "Haikei app",
      category: "icon",
      link: 'https://haikei.app',
      img: "./src/asset-122.jpg",
      desc: `Haikei is a web app to generate unique SVG shapes, backgrounds, and patterns`,
    },
    {
      id: 123,
      title: "Hero Icons",
      category: "icon",
      link: 'https://heroicons.com',
      img: "./src/asset-123.jpg",
      desc: `Beautiful hand-crafted SVG icons, by the makers of Tailwind CSS.`,
    },
    {
      id: 124,
      title: "Health Icon",
      category: "icon",
      link: 'https://healthicons.org',
      img: "./src/asset-124.jpg",
      desc: `Free for use in your next commercial or personal project. Editing is ok`,
    },
    {
      id: 125,
      title: "Palms Casa",
      category: "illustration",
      link: 'https://palms.casa',
      img: "./src/asset-125.jpg",
      desc: `free palm ilustrator.`,
    },
    {
      id: 126,
      title: "Story Set",
      category: "illustration",
      link: 'https://storyset.com',
      img: "./src/asset-126.jpg",
      desc: `Edit and animate all our customizable illustrations to enhance your projects totally free. Start now to be creative in our online editor.`,
    },
    {
      id: 127,
      title: "Sketch Valley",
      category: "illustration",
      link: 'https://sketchvalley.com',
      img: "./src/asset-127.jpg",
      desc: `Hand-drawn free vector illustration resources for your projects. All UX/UI flat.`,
    },
    {
      id: 128,
      title: "unDraw",
      category: "illustration",
      link: 'https://undraw.co',
      img: "./src/asset-128.jpg",
      desc: `unDraw · Open-source illustrations for any idea you can imagine and create..`,
    },
    {
      id: 129,
      title: "Blush Design",
      category: "illustration",
      link: 'https://blush.design/',
      img: "./src/asset-129.jpg",
      desc: `Blush makes it easy to add free illustrations to your designs. Play with fully customizable graphics made by artists across the globe.`,
    },
    {
      id: 130,
      title: "Drawkit",
      category: "illustration",
      link: 'https://www.drawkit.io',
      img: "./src/asset-130.jpg",
      desc: `Free and premium vector SVG illustrations for you to use on your next project, no attribution required! Vector illustrations, packs, icons and more`,
    },
    {
      id: 131,
      title: "Open Doodles",
      category: "illustration",
      link: 'https://www.opendoodles.com',
      img: "./src/asset-131.jpg",
      desc: `A library of sketchy illustrations of people free for personal and commercial use.`,
    },
    {
      id: 132,
      title: "Ira Design",
      category: "illustration",
      link: 'https://iradesign.io',
      img: "./src/asset-132.jpg",
      desc: `For developers. Start building your mobile app in no time. Simply select the components you like and start customising to suit your needs. ·.`,
    },
    {
      id: 133,
      title: "UI Garage",
      category: "inspiration",
      link: 'https://uigarage.net',
      img: "./src/asset-133.jpg",
      desc: `Daily UI inspiration & patterns for designers, developers to find inspiration, tools and the best resources for your project.`,
    },
    {
      id: 134,
      title: "Dribbble",
      category: "inspiration",
      link: 'https://dribbble.com',
      img: "./src/asset-134.jpg",
      desc: `Dribbble is where designers gain inspiration, feedback, community, and jobs and is your best resource to discover and connect with designers worldwide.`,
    },
    {
      id: 135,
      title: "Behance",
      category: "inspiration",
      link: 'https://www.behance.net',
      img: "./src/asset-135.jpg",
      desc: `Behance is the world's largest creative network for showcasing and discovering creative work.`,
    },
    {
      id: 136,
      title: "Mobbin Design",
      category: "inspiration",
      link: 'https://mobbin.design/',
      img: "./src/asset-136.jpg",
      desc: `Save hours of UI & UX research with our library of 50000+ fully searchable mobile app screenshots.`,
    },
    {
      id: 137,
      title: "Awwwards",
      category: "inspiration",
      link: 'https://www.awwwards.com',
      img: "./src/asset-137.jpg",
      desc: `Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world..`,
    },
    {
      id: 138,
      title: "Muzli",
      category: "inspiration",
      link: 'https://muz.li',
      img: "./src/asset-138.jpg",
      desc: `Muzli curates the latest content from hundreds of online design, tech & news publications..`,
    },
    {
      id: 139,
      title: "upLabs",
      category: "inspiration",
      link: 'https://www.uplabs.com',
      img: "./src/asset-139.jpg",
      desc: `UpLabs is the place to find high-quality design resources for designers, creative agencies and developers.`,
    },
    {
      id: 140,
      title: "Siiimple",
      category: "inspiration",
      link: 'https://siiimple.com',
      img: "./src/asset-140.jpg",
      desc: `Siiimple is a minimalist css design gallery.`,
    },
    {
      id: 141,
      title: "Css Design Awards",
      category: "inspiration",
      link: 'https://www.cssdesignawards.com',
      img: "./src/asset-141.jpg",
      desc: `CSS Design Awards. Be inspired, Be inspiring. Submit your website to the world's best CSS awards for a chance to win Site of the Day.`,
    },
    {
      id: 142,
      title: "CSS Winner",
      category: "inspiration",
      link: 'https://www.csswinner.com',
      img: "./src/asset-142.jpg",
      desc: `CSS Winner is a website design award gallery for web designers and developers to showcase their best web design works and win css winner.`,
    },
    {
      id: 143,
      title: "Beta List",
      category: "inspiration",
      link: 'https://betalist.com',
      img: "./src/asset-143.jpg",
      desc: `BetaList is a community of makers and early adopters showcasing their startups and exchanging feedback.`,
    },
    {
      id: 144,
      title: "Product Hunt",
      category: "inspiration",
      link: 'https://www.producthunt.com',
      img: "./src/asset-144.jpg",
      desc: `Product Hunt is a curation of the best new products, every day. Discover the latest mobile apps,.`,
    },
    {
      id: 145,
      title: "LookUp Design",
      category: "inspiration",
      link: 'https://lookup.design',
      img: "./src/asset-145.jpg",
      desc: `Browse handpicked ui and ux design examples and find inspiration for your next website or app.`,
    },
    {
      id: 146,
      title: "Best Folios",
      category: "inspiration",
      link: 'https://www.bestfolios.com/portfolios',
      img: "./src/asset-146.jpg",
      desc: `The largest collection of the best portfolio websites from top designers in the industry. All Portfolios; UX Design; Graphic Design.`,
    },
    {
      id: 147,
      title: "IJOC",
      category: "journal",
      link: 'https://ijoc.org/index.php/ijoc',
      img: "./src/asset-147.jpg",
      desc: `The International Journal of Communication is an online, multi-media, academic journal that adheres to the highest standards of peer review and engages`,
    },
    {
      id: 148,
      title: "IJDesign",
      category: "journal",
      link: 'http://www.ijdesign.org/',
      img: "./src/asset-148.jpg",
      desc: `The International Journal of Design is a peer-reviewed, open-access journal devoted to publishing research papers in all fields of design.`,
    },
    {
      id: 149,
      title: "IJEA",
      category: "journal",
      link: 'http://www.ijea.org',
      img: "./src/asset-149.jpg",
      desc: `IJEA is an open access platform for scholarly dialogue`,
    },
    {
      id: 150,
      title: "IJSTR",
      category: "journal",
      link: 'https://ijstr.org',
      img: "./src/asset-150.jpg",
      desc: `IJSTR is an open access quality publication of peer reviewed and refereed international journals. IJSTR calls for research papers.`,
    },
    {
      id: 151,
      title: "JMM",
      category: "journal",
      link: 'https://jmm-net.com',
      img: "./src/asset-151.jpg",
      desc: `Journal of Marketing Management is a double blind peer reviewed international academic journal that publishes scientific research papers on the contemporary`,
    },
    {
      id: 152,
      title: "Sciene Direct",
      category: "journal",
      link: 'https://www.sciencedirect.com',
      img: "./src/asset-152.jpg",
      desc: `ScienceDirect is the world's leading source for scientific, technical, and medical research. Explore journals, books and articles.`,
    },
    {
      id: 153,
      title: "Online Library",
      category: "journal",
      link: 'https://onlinelibrary.wiley.com',
      img: "./src/asset-153.jpg",
      desc: `One of the largest and most authoritative collections of online journals, books, and research resources, covering life, health, social, and physical`,
    },
    {
      id: 154,
      title: "Indersciene",
      category: "journal",
      link: 'https://www.inderscience.com',
      img: "./src/asset-154.jpg",
      desc: `Munasinghe for this outstanding and significant achievement. International Journal of Sustainable Agricultural Management and Informatics indexed by Clarivate`,
    },
    {
      id: 155,
      title: "Emerald",
      category: "journal",
      link: 'https://www.emerald.com/insight/',
      img: "./src/asset-155.jpg",
      desc: `Discover impactful Journals, Books & Case Studies from Emerald Publishing on Emerald Insight.`,
    },
    {
      id: 156,
      title: "Invoice",
      category: "lifehack",
      link: 'https://invoicequick.com',
      img: "./src/asset-156.jpg",
      desc: `Print invoice`,
    },
    {
      id: 157,
      title: "10 minutes email",
      category: "lifehack",
      link: 'http://10minutesmail.com',
      img: "./src/asset-157.jpg",
      desc: `Get free email to create trial account`,
    },
    {
      id: 158,
      title: "Essay Typer",
      category: "lifehack",
      link: 'http://www.essaytyper.com',
      img: "./src/asset-158.jpg",
      desc: `EssayTyper uses a patented combination of magic and wikipedia to help you write your essay - fast!`,
    },
    {
      id: 159,
      title: "Name Lix",
      category: "lifehack",
      link: 'https://namelix.com',
      img: "./src/asset-159.jpg",
      desc: `Namelix is a free business name generator that uses artificial intelligence technology to create dynamic business names from a set of keywords selected by the user.`,
    },
    {
      id: 160,
      title: "CheckUserName",
      category: "lifehack",
      link: 'https://checkusernames.com',
      img: "./src/asset-160.jpg",
      desc: `checkusernames.com	is a quick and useful tool for checking your brand across major social networks, in one simple search.`,
    },
    {
      id: 161,
      title: "Answer The Public",
      category: "lifehack",
      link: 'https://answerthepublic.com',
      img: "./src/asset-161.jpg",
      desc: `AnswerThePublic listens into autocomplete data from search engines like Google then quickly cranks out every useful phrase and question people are asking around your keyword.`,
    },
    {
      id: 162,
      title: "Import Yeti",
      category: "lifehack",
      link: 'https://www.importyeti.com',
      img: "./src/asset-162.jpg",
      desc: `ImportYeti is the combination of some downtime created by the Corona Virus and my desire to give back to the eCom community that has given me so much.`,
    },
    {
      id: 163,
      title: "Remove bg",
      category: "lifehack",
      link: 'https://remove.bg',
      img: "./src/asset-163.jpg",
      desc: `Remove image backgrounds automatically in 5 seconds with just one click. Don't spend hours manually picking pixels.`,
    },
    {
      id: 164,
      title: "Compress JPEG",
      category: "lifehack",
      link: 'https://compressjpeg.com',
      img: "./src/asset-164.jpg",
      desc: `Compress JPEG images and photos for displaying on web pages, sharing on social networks or sending by email.`,
    },
    {
      id: 165,
      title: "Shorcut Design",
      category: "lifehack",
      link: 'https://shortcuts.design',
      img: "./src/asset-165.jpg",
      desc: `Shortcuts.design is the ultimate shortcut reference for designers. Charge your workflow with all the shortcuts of your favorite tools like Figma and Windows`,
    },
    {
      id: 166,
      title: "Get Waves",
      category: "lifehack",
      link: 'https://getwaves.io',
      img: "./src/asset-166.jpg",
      desc: `Get Waves`,
    },
    {
      id: 167,
      title: "BrandMark",
      category: "lifehack",
      link: 'https://brandmark.io',
      img: "./src/asset-167.jpg",
      desc: `build logos.`,
    },
    {
      id: 168,
      title: "Panzoid",
      category: "lifehack",
      link: 'https://panzoid.com/',
      img: "./src/asset-168.jpg",
      desc: `Powerful, free online tools and community for creating beautiful custom content.`,
    },
    {
      id: 169,
      title: "Shortly ai",
      category: "lifehack",
      link: 'https://www.shortlyai.com',
      img: "./src/asset-169.jpg",
      desc: `write blog with ai.`,
    },
    {
      id: 170,
      title: "Vocal Remover",
      category: "lifehack",
      link: 'https://vocalremover.org',
      img: "./src/asset-170.jpg",
      desc: `Split music into separated vocals and instrumental track. Perfect for making karaoke backing tracks or accapella extractor.`,
    },
    {
      id: 171,
      title: "The Inpaint",
      category: "lifehack",
      link: 'https://theinpaint.com',
      img: "./src/asset-171.jpg",
      desc: `Customize Folder Icon and Color in One Click!.`,
    },
    {
      id: 172,
      title: "Tiny PNG",
      category: "lifehack",
      link: 'https://tinypng.com',
      img: "./src/asset-172.jpg",
      desc: `compress png.`,
    },
    {
      id: 173,
      title: "Resume",
      category: "lifehack",
      link: 'https://resume.com',
      img: "./src/asset-173.jpg",
      desc: `Create a professional resume with the only truly free resume builder online. Browse our templates, then easily build and share your resume.`,
    },
    {
      id: 174,
      title: "WebCode Generator",
      category: "lifehack",
      link: 'https://webcode.tools/generators/css',
      img: "./src/asset-174.jpg",
      desc: `The ultimate CSS generator. Learn CSS with our generators and preview your results! Start now without any CSS experience.`,
    },
    {
      id: 175,
      title: "UI Gradient",
      category: "lifehack",
      link: 'https://uigradients.com',
      img: "./src/asset-175.jpg",
      desc: `A handpicked collection of beautiful color gradients for designers and developers.`,
    },
    {
      id: 176,
      title: "Plagiarism Detector",
      category: "lifehack",
      link: 'https://plagiarismdetector.net/',
      img: "./src/asset-176.jpg",
      desc: `Plagiarism Detector adalah perangkat lunak pemeriksa esai yang bebas dan cerdas.`,
    },
    {
      id: 177,
      title: "Keyframe app",
      category: "lifehack",
      link: 'https://keyframes.app',
      img: "./src/asset-177.jpg",
      desc: `Keyframes helps you write better CSS. Dead simple visual tools to help you generate CSS for your projects.`,
    },
    {
      id: 178,
      title: "Hotpot ai",
      category: "lifehack",
      link: 'https://hotpot.ai',
      img: "./src/asset-178.jpg",
      desc: `Hotpot.ai is an easy way to create device mockups, logos, social media ads, and other graphics.`,
    },
    {
      id: 179,
      title: "Dareboost",
      category: "lifehack",
      link: 'https://www.dareboost.com',
      img: "./src/asset-179.jpg",
      desc: `Quality Web Check.`,
    },
    {
      id: 180,
      title: "Lit Maps",
      category: "lifehack",
      link: 'https://app.litmaps.co',
      img: "./src/asset-180.jpg",
      desc: `Litmaps is a new environment for discovering scientific literature.`,
    },
    {
      id: 181,
      title: "Previewed app",
      category: "mockup",
      link: 'https://previewed.app/',
      img: "./src/asset-181.jpg",
      desc: `Previewed to create stunning 3D image shots and animations for your app. Choose from hundreds of ready made mockups.`,
    },
    {
      id: 182,
      title: "JItter Video",
      category: "lifehack",
      link: 'https://jitter.video',
      img: "./src/asset-182.jpg",
      desc: `Animate your designs easily. Export your creations as videos or GIFs.`,
    },
    {
      id: 183,
      title: "LS Graphics",
      category: "mockup",
      link: 'https://www.ls.graphics/',
      img: "./src/asset-183.jpg",
      desc: `Vivid illustrations will add color to your story. Great illustrations for website and mobile applications.`,
    },
    {
      id: 184,
      title: "UI Mock app",
      category: "mockup",
      link: 'https://www.uimock.app',
      img: "./src/asset-184.jpg",
      desc: `A tool for designers to show off their work professionally on several platforms.`,
    },
    {
      id: 185,
      title: "Smart MockUp",
      category: "mockup",
      link: 'https://smartmockups.com',
      img: "./src/asset-185.jpg",
      desc: `Create professional mockups right inside your browser, even on the go, Forget about spending hours learning how to use Photoshop.`,
    },
    {
      id: 186,
      title: "Pixeden",
      category: "mockup",
      link: 'https://www.pixeden.com',
      img: "./src/asset-186.jpg",
      desc: `Pixeden is hard at work providing quality web resources. Download all our free web and graphic design templates, and get access to all our Premium files .`,
    },
    {
      id: 187,
      title: "Mockup Design",
      category: "mockup",
      link: 'https://mockups-design.com',
      img: "./src/asset-187.jpg",
      desc: `Download free mockups! Mockups Design is a site where you can find free premium mockups that can be used in your private and commercial work.`,
    },
    {
      id: 188,
      title: "Things Morflax",
      category: "mockup",
      link: 'https://things.morflax.com',
      img: "./src/asset-188.jpg",
      desc: `Generate 3D device mockup in a quick and engaging way. Simple, fast and powerful tool. Everything in your browser.`,
    },
    {
      id: 189,
      title: "Neede",
      category: "notes",
      link: 'https://neede.co',
      img: "./src/asset-189.jpg",
      desc: `A collection of useful online resources for designers.`,
    },
    {
      id: 190,
      title: "EverNote",
      category: "notes",
      link: 'https://www.evernote.design',
      img: "./src/asset-190.jpg",
      desc: `All in One Bookmark Links for Designer`,
    },
    {
      id: 191,
      title: "btw open",
      category: "notes",
      link: 'https://www.btw.so/open-source-alternatives',
      img: "./src/asset-191.jpg",
      desc: `All in one Bookmark`,
    },
    {
      id: 192,
      title: "Chekclist Design",
      category: "notes",
      link: 'https://www.checklist.design',
      img: "./src/asset-192.jpg",
      desc: `Checklist Design is a curated list of checklists ranging from website pages, to UI components, all the way to branding assets.`,
    },
    {
      id: 193,
      title: "Notes UI UX",
      category: "notes",
      link: 'https://www.dwinawan.com/bookmark#',
      img: "./src/asset-174.jpg",
      desc: `All in one`,
    },
    {
      id: 194,
      title: "Hidden Tools Dev",
      category: "notes",
      link: 'https://hiddentools.dev',
      img: "./src/asset-194.jpg",
      desc: `Discover a wide collection tools.`,
    },
    {
      id: 195,
      title: "Top Coder",
      category: "practice",
      link: 'https://www.topcoder.com',
      img: "./src/asset-195.jpg",
      desc: `Topcoder is home to the world's largest community of designers, developers, and data scientists. Allowing you the freedom to start and execute faster.`,
    },
    {
      id: 174,
      title: "WebCode Generator",
      category: "lifehack",
      link: 'https://webcode.tools/generators/css',
      img: "./src/asset-174.jpg",
      desc: `The ultimate CSS generator. Learn CSS with our generators and preview your results! Start now without any CSS experience.`,
    },
    {
      id: 196,
      title: "CodeByte",
      category: "practice",
      link: 'https://coderbyte.com',
      img: "./src/asset-196.jpg",
      desc: `Challenge yourself to code and interview better. · Coderbyte is the #1 platform for 1,000,000+ developers that want to take their careers to the next level.`,
    },
    {
      id: 197,
      title: "HackerRank",
      category: "practice",
      link: 'https://www.hackerrank.com',
      img: "./src/asset-197.jpg",
      desc: `HackerRank is the market-leading technical assessment and remote interview solution for hiring developers. Learn how to hire technical talent from anywhere!`,
    },
    {
      id: 198,
      title: "Hacker Earth",
      category: "practice",
      link: 'https://www.hackerearth.com',
      img: "./src/asset-198.jpg",
      desc: `HackerEarth lets you engage or source top developers with hackathons, while also enabling you to assess, interview and upskill them with ease.`,
    },
    {
      id: 199,
      title: "Leet Code",
      category: "practice",
      link: 'https://leetcode.com',
      img: "./src/asset-199.jpg",
      desc: `LeetCode is the best platform to help you enhance your skills, expand your knowledge and prepare for technical interviews.`,
    },
    {
      id: 200,
      title: "Code Monkey",
      category: "practice",
      link: 'https://www.codemonkey.com',
      img: "./src/asset-200.jpg",
      desc: `CodeMonkey is a leading coding for kids program. Through its award-winning courses, millions of students learn how to code in real programming languages.`,
    },
    {
      id: 201,
      title: "TLX Toki",
      category: "practice",
      link: 'https://tlx.toki.id',
      img: "./src/asset-201.jpg",
      desc: `Competitive Programming Platform. Indonesia's #1 platform for honing your competitive programming skills, brought to you by Ikatan Alumni TOKI.`,
    },
    {
      id: 202,
      title: "UX Tools",
      category: "practice",
      link: 'https://uxtools.co/challenges',
      img: "./src/asset-202.jpg",
      desc: `UI UX Challenges Contest.`,
    },
    {
      id: 203,
      title: "UpLabs UI Challenges",
      category: "practice",
      link: 'https://www.uplabs.com/challenges',
      img: "./src/asset-203.jpg",
      desc: `UI UX Challenges Contest.`,
    },
    {
      id: 204,
      title: "CryptoZombie",
      category: "practice",
      link: 'https://cryptozombies.io',
      img: "./src/asset-204.jpg",
      desc: `BlockChain Practice`,
    },
    {
      id: 205,
      title: "frontendmentor",
      category: "practice",
      link: 'https://www.frontendmentor.io',
      img: "./src/asset-205.jpg",
      desc: `Improve your front-end skills by building real projects. Solve real-world HTML, CSS and JavaScript challenges whilst working to professional designs.`,
    },
    {
      id: 206,
      title: "Clone Wars",
      category: "practice",
      link: 'http://gourav.io/clone-wars',
      img: "./src/asset-206.jpg",
      desc: `Open-source clones and alternatives of popular sites like Airbnb, Amazon, Instagram, Netflix, Tiktok, Spotify, Whatsapp, Youtube, etc. List contains source code, tutorials, demo links, tech stack, and GitHub stars count. Great for learning purpose!.`,
    },
    {
      id: 207,
      title: "All Free Stock",
      category: "resource",
      link: 'https://allthefreestock.com',
      img: "./src/asset-207.jpg",
      desc: `AllTheFreeStock.com is a curated list of free stock images, audio and videos. Find all the best free stock images and videos in one place.`,
    },
    {
      id: 208,
      title: "Finviz",
      category: "lifehack",
      link: 'https://finviz.com',
      img: "./src/asset-208.jpg",
      desc: `Stock screener for investors and traders, financial visualizations..`,
    },
    {
      id: 209,
      title: "The Noun Project",
      category: "resource",
      link: 'https://thenounproject.com',
      img: "./src/asset-209.jpg",
      desc: `Noun Project features the most diverse collection of icons and stock photos ever. Download SVG and PNG.`,
    },
    {
      id: 210,
      title: "Freepik",
      category: "resource",
      link: 'https://www.freepik.com',
      img: "./src/asset-210.jpg",
      desc: `Millions of Free Graphic Resources. ✓ Vectors ✓ Stock Photos ✓ PSD ✓ Icons ✓ All that you need for your Creative Projects.`,
    },
    {
      id: 211,
      title: "Vecteezy",
      category: "resource",
      link: 'https://www.vecteezy.com',
      img: "./src/asset-211.jpg",
      desc: `Explore royalty-free vectors, clipart graphics, icons, stock photos, stock videos, backgrounds, patterns, banners, and designs from artists around the`,
    },
    {
      id: 212,
      title: "Unsplash",
      category: "resource",
      link: 'https://unsplash.com',
      img: "./src/asset-212.jpg",
      desc: `Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.`,
    },
    {
      id: 213,
      title: "Pexels",
      category: "resource",
      link: 'https://www.pexels.com',
      img: "./src/asset-213.jpg",
      desc: `Free stock photos and videos you can use everywhere. ✓ High-quality ✓ 100% free ✓ No attribution needed.`,
    },
    {
      id: 214,
      title: "Pixabay",
      category: "resource",
      link: 'https://pixabay.com',
      img: "./src/asset-214.jpg",
      desc: `Pixabay is a vibrant community of creatives, sharing copyright free images, videos and music`,
    },
    {
      id: 215,
      title: "Kaboompics",
      category: "resource",
      link: 'https://kaboompics.com',
      img: "./src/asset-215.jpg",
      desc: `Every single day new photos of the highest quality are added to Kaboompics. You can download and use them for your own purposes.`,
    },
    {
      id: 216,
      title: "StockSnap",
      category: "resource",
      link: 'http://stocksnap.io',
      img: "./src/asset-216.jpg",
      desc: `The #1 source for beautiful free photos. High quality and high resolution stock images free from all copyright restrictions (CC0)`,
    },
    {
      id: 217,
      title: "Unblast",
      category: "resource",
      link: 'https://unblast.com',
      img: "./src/asset-217.jpg",
      desc: `Selection of fine and free design resources made by the world's best designers.`,
    },
    {
      id: 218,
      title: "Pxfuel",
      category: "resource",
      link: 'https://www.pxfuel.com',
      img: "./src/asset-218.jpg",
      desc: `Millions of public domain stock photos released under creative common zero lincense, all are free for commercial use.`,
    },
    {
      id: 219,
      title: "HTML5 Up",
      category: "template",
      link: 'https://html5up.net',
      img: "./src/asset-219.jpg",
      desc: `HTML5up has you covered. This collection of slick, animated websites are free to download – and use.`,
    },
    {
      id: 220,
      title: "Powerpointify",
      category: "template",
      link: 'https://powerpointify.com',
      img: "./src/asset-220.jpg",
      desc: `Find modern free Powerpoint templates for beautiful presentations. Download PPT files created with high-quality graphics`,
    },
    {
      id: 221,
      title: "Toolplate",
      category: "template",
      link: 'https://www.tooplate.com',
      img: "./src/asset-221.jpg",
      desc: `Tooplate brings you a variety of free HTML templates for your business websites, digital marketing pages, and personal portfolios.`,
    },
    {
      id: 222,
      title: "Themes for app",
      category: "template",
      link: 'https://themesfor.app',
      img: "./src/asset-222.jpg",
      desc: `Beautiful, free bootstrap themes and landing pages that you can download and use for your startup and side project.`,
    },
    {
      id: 223,
      title: "One Page Love",
      category: "template",
      link: 'https://onepagelove.com',
      img: "./src/asset-223.jpg",
      desc: `One Page Love is a One Page website design gallery showcasing the best Single Page websites, templates and resources.`,
    },
    {
      id: 224,
      title: "Zero Theme",
      category: "template",
      link: 'https://zerotheme.com',
      img: "./src/asset-224.jpg",
      desc: `Html5 Website Templates designed by #Mik. Free download all templates at Zerotheme : responsive templates, bootstrap themes, ecommerce themes`,
    },
    {
      id: 225,
      title: "Start Bootstrap",
      category: "template",
      link: 'https://startbootstrap.com',
      img: "./src/asset-225.jpg",
      desc: `Start Bootstrap develops free to download, open source Bootstrap 5 themes, templates, and snippets and creates guides and tutorials to help you learn more.`,
    },
    {
      id: 226,
      title: "Styleshout",
      category: "template",
      link: 'https://styleshout.com',
      img: "./src/asset-226.jpg",
      desc: `Download our collection of handcrafted free website templates. We make premium-like free website templates that look awesome and easy to use.`,
    },
    {
      id: 227,
      title: "free html5",
      category: "template",
      link: 'https://freehtml5.co',
      img: "./src/asset-227.jpg",
      desc: `FreeHTML5.co is dedicated to provide extraordinary and premium-like free html5 bootstrap templates for web designers and developers.`,
    },
    {
      id: 228,
      title: "Tempaltemo",
      category: "template",
      link: 'https://templatemo.com',
      img: "./src/asset-228.jpg",
      desc: `Download 565+ free HTML CSS website templates that included 140+ responsive Bootstrap themes from templatemo and use them for your sites.`,
    },
    {
      id: 229,
      title: "HTML Template",
      category: "template",
      link: 'https://htmltemplates.co',
      img: "./src/asset-229.jpg",
      desc: `Free HTML Templates. The ultimate showcase of beautiful high quality free HTML and CSS website templates.`,
    },
    {
      id: 230,
      title: "Tailwind UI Kit",
      category: "template",
      link: 'https://tailwinduikit.com',
      img: "./src/asset-230.jpg",
      desc: `The only UI kit for tailwind css to offer 600+ components 30 templates. Integrations for React, Angular, Vue, and Wordpress.`,
    },
    {
      id: 231,
      title: "SlidesGo",
      category: "template",
      link: 'https://slidesgo.com',
      img: "./src/asset-231.jpg",
      desc: `Discover the best Google Slides themes and PowerPoint templates you can use in your presentations - 100% Free for any use.`,
    },
    {
      id: 232,
      title: "Slides Carnival",
      category: "template",
      link: 'https://slidescarnival.com',
      img: "./src/asset-232.jpg",
      desc: `SlidesCarnival templates have all the elements you need to effectively communicate your message and impress your`,
    },
    {
      id: 233,
      title: "Presentation Go",
      category: "template",
      link: 'https://www.presentationgo.com',
      img: "./src/asset-233.jpg",
      desc: `PresentationGO is a large and growing library of free templates for PowerPoint and Google Slides.`,
    },
    {
      id: 234,
      title: "Material UI",
      category: "template",
      link: 'https://material-ui.com',
      img: "./src/asset-234.jpg",
      desc: `React components for faster and easier web development. Build your own design system, or start with Material Design.`,
    },
    {
      id: 235,
      title: "Windy",
      category: "template",
      link: 'https://windy-docs.vercel.app',
      img: "./src/asset-235.jpg",
      desc: `React UI Kit`,
    },
    {
      id: 236,
      title: "Grommet",
      category: "template",
      link: 'https://v2.grommet.io',
      img: "./src/asset-236.jpg",
      desc: `Grommet is a react-based framework that provides accessibility, modularity, responsiveness, and theming in a tidy package..`,
    },
    {
      id: 237,
      title: "Freebies Bug",
      category: "template",
      link: 'https://freebiesbug.com',
      img: "./src/asset-237.jpg",
      desc: `Freebiesbug is a web design blog showcasing free high-quality design resources like PSD files, HTML website templates, fonts and other cool stuff`,
    },
    {
      id: 238,
      title: "Maze",
      category: "lifehack",
      link: 'https://maze.co',
      img: "./src/asset-238.jpg",
      desc: `Get user feedback with Maze's remote testing platform..`,
    },
    {
      id: 239,
      title: "ProQuest",
      category: "journal",
      link: 'https://proquest.com',
      img: "./src/asset-239.jpg",
      desc: `ProQuest powers research in academic, corporate, government, public and school libraries around the world with unique content.`,
    },
    {
      id: 240,
      title: "Books SC",
      category: "journal",
      link: 'https://booksc.org',
      img: "./src/asset-240.jpg",
      desc: `TElectronic library. Download books free. Finding books | BookSC. Download books for free. Find books.`,
    },
    {
      id: 241,
      title: "CiteSeerX",
      category: "journal",
      link: 'https://citeseerx.ist.psu.edu',
      img: "./src/asset-241.jpg",
      desc: `Scientific Literature Digital Library incorporating autonomous citation indexing, awareness and tracking, citation context, related document retrieval,`,
    },
    {
      id: 242,
      title: "DOAJ",
      category: "journal",
      link: 'https://doaj.org',
      img: "./src/asset-242.jpg",
      desc: `DOAJ is a community-curated online directory that indexes and provides access to high quality, open access, peer-reviewed journals.`,
    },
    {
      id: 243,
      title: "UOP International",
      category: "journal",
      link: 'https://www.uopinternational.org',
      img: "./src/asset-243.jpg",
      desc: `UOP International is the top-rated university in Stockton, which offers 60+ undergraduate and graduate programs. Find out more about our academics!`,
    },
    {
      id: 244,
      title: "Absurd Design",
      category: "illustration",
      link: 'https://absurd.design',
      img: "./src/asset-244.jpg",
      desc: `Download surrealist illustrations. Use free vector art for your landing pages, presentations and apps.`,
    },
    {
      id: 245,
      title: "Open Peeps",
      category: "illustration",
      link: 'https://www.openpeeps.com',
      img: "./src/asset-245.jpg",
      desc: `Open Peeps is a hand-drawn illustration library to create scenes of people. You can use them in product illustration, marketing, comics, product states,`,
    },
    {
      id: 246,
      title: "Udemy",
      category: "course",
      link: 'https://udemy.com',
      img: "./src/asset-246.jpg",
      desc: `Find the right instructor for you. Choose from many topics, skill levels, and languages. Shop thousands of high-quality on-demand online courses.`,
    },
    {
      id: 247,
      title: "Petani Code",
      category: "course",
      link: 'https://www.petanikode.com/tutorial/',
      img: "./src/asset-247.jpg",
      desc: `Website tempat belajar budidaya kode (coding/pemrograman) dengan tutorial terupdate dan mudah dipahami pemula.`,
    },
    {
      id: 248,
      title: "SINTA",
      category: "journal",
      link: 'https://sinta.ristekbrin.go.id/journals',
      img: "./src/asset-248.jpg",
      desc: `International Journal of Evaluation and Research in Education (IJERE): Institute of Advanced Engineering and Science (IAES)`,
    },
    {
      id: 249,
      title: "CSS Batlle",
      category: "practice",
      link: 'https://cssbattle.dev',
      img: "./src/asset-249.jpg",
      desc: `Welcome to CSSBattle! CSS code-golfing game is here! Use your CSS skills to replicate targets with smallest possible code. .`,
    },
    {
      id: 250,
      title: "Upwork",
      category: "freelance",
      link: 'https://www.upwork.com',
      img: "./src/asset-250.jpg",
      desc: `Upwork connects businesses with freelancers, independent talent, and agencies around the globe.`,
    },
    {
      id: 251,
      title: "Jobs CheatSheet",
      category: "cheatsheet",
      link: 'https://docs.google.com/spreadsheets/d/12VnIPTO24m7_UKG_7SqTyUSwqRQRfgp_edLJNkKuMNE/edit#gid=1242740900',
      img: "./src/asset-251.jpg",
      desc: `CheatSheet for you to looking jobs`,
    },
    {
      id: 252,
      title: "Intern CheatSheet",
      category: "cheatsheet",
      link: 'https://docs.google.com/spreadsheets/d/1JLkDtQwbuRm1hpL0NAkdjbHUl_C87RUof07YbcrdyhU/edit#gid=958041414',
      img: "./src/asset-252.jpg",
      desc: `CheatSheet for you to looking jobs`,
    },
    {
      id: 253,
      title: "UIUX CheatSheet",
      category: "cheatsheet",
      link: 'https://docs.google.com/spreadsheets/d/12VnIPTO24m7_UKG_7SqTyUSwqRQRfgp_edLJNkKuMNE/edit#gid=1242740900',
      img: "./src/asset-253.jpg",
      desc: `CheatSheet for you to want become UI UX`,
    },
    {
      id: 254,
      title: "Kern Type",
      category: "practice",
      link: 'https://type.method.ac',
      img: "./src/asset-254.jpg",
      desc: `A game to learn how to kern type.`,
    },
    {
      id: 255,
      title: "Uxcel",
      category: "practice",
      link: 'https://uxcel.com',
      img: "./src/asset-255.jpg",
      desc: `Uxcel is an amazing community of designers focused on learning and validating their design skills. Learn Design. Access an extensive library of UX/UI design.`,
    },
    {
      id: 256,
      title: "Can't Unsee",
      category: "practice",
      link: 'https://cantunsee.space',
      img: "./src/asset-256.jpg",
      desc: `Can't Unsee. Can't Unsee. Can't Unsee. Can't Unsee. coin 000000. card. Select the design that is most correct. `,
    },
    {
      id: 257,
      title: "Synethesia",
      category: "lifehack",
      link: 'https://synthesia.io',
      img: "./src/asset-257.jpg",
      desc: `Synthesia AI Video platform. Create videos in minutes, not weeks · Create your videos in 40+ different languages.`,
    },
    {
      id: 258,
      title: "Many Pixels",
      category: "illustration",
      link: 'https://manypixels.co',
      img: "./src/asset-258.jpg",
      desc: `ManyPixels is a simple and affordable subscription-based, unlimited graphic design service. Get Your Graphic Design Team in a Few Clicks.`,
    },
    {
      id: 259,
      title: "Dicoding",
      category: "course",
      link: 'https://dicoding.com',
      img: "./src/asset-259.jpg",
      desc: `Dicoding adalah menjadi platform edukasi teknologi terdepan yang mendorong akses literasi digital yang lebih luas untuk semua.`,
    },
    {
      id: 260,
      title: "FreeCodeCamp",
      category: "course",
      link: 'https://www.freecodecamp.org/learn/',
      img: "./src/asset-260.jpg",
      desc: `freeCodeCamp is a proven path to your first software developer job.`,
    },
    {
      id: 261,
      title: "NetaCad",
      category: "course",
      link: 'https://www.netacad.com/courses/programming/pcap-programming-essentials-python',
      img: "./src/asset-261.jpg",
      desc: `Programming skills open you up to careers in almost any industry and are required if you want to continue to more advanced and higher paying software development and engineering roles.`,
    },
    {
      id: 262,
      title: "Data Flair",
      category: "course",
      link: 'https://data-flair.training/python-course/',
      img: "./src/asset-262.jpg",
      desc: `A perfect blend of in-depth Python theoretical knowledge and strong practical skills, this Free course for Python introduces real-time Python projects to give you a headstart in learning Python and enables you to bag top Python jobs in the industry.`,
    },
    {
      id: 263,
      title: "Test Automation",
      category: "course",
      link: 'https://testautomationu.applitools.com',
      img: "./src/asset-263.jpg",
      desc: `Free test automation courses with videos, transcripts, quizzes, credits, ranks badges, and certificates!`,
    },
    {
      id: 264,
      title: "Harvard CV Template",
      category: "cheatsheet",
      link: 'https://ocs.fas.harvard.edu/resumes-cvs-cover-letters',
      img: "./src/asset-264.jpg",
      desc: `Free Template CV from Harvard`,
    },
    {
      id: 265,
      title: "Glints",
      category: "freelance",
      link: 'https://glints.com/id/',
      img: "./src/asset-265.jpg",
      desc: `Tersedia Untuk Berbagai Level Mulai Dari Internship, Fresh Graduate dan Professional. Proses Interview Cepat, Fleksibel, Banyak Tunjangan, Jenjang Karir Yang Pasti.`,
    },
    {
      id: 266,
      title: "Dana Jobs",
      category: "freelance",
      link: 'https://danaid.bamboohr.com/jobs',
      img: "./src/asset-266.jpg",
      desc: `Update Dana Jobs / Internship`,
    },
    {
      id: 267,
      title: "State of JS",
      category: "documentation",
      link: 'https://stateofjs.com',
      img: "./src/asset-267.jpg",
      desc: `Describing around JS`,
    },
    {
      id: 268,
      title: "WowKi",
      category: "cheatsheet",
      link: 'https://wokwi.com/',
      img: "./src/asset-268.jpg",
      desc: `Simulation for rasberry Pi, IOT`,
    },
    {
      id: 269,
      title: "Material IO",
      category: "cheatsheet",
      link: 'https://material.io',
      img: "./src/asset-269.jpg",
      desc: `Material for Design UI UX`,
    },
    {
      id: 270,
      title: "My Color Space",
      category: "color",
      link: 'https://mycolor.space',
      img: "./src/asset-270.jpg",
      desc: `Generate 1 to many colors`,
    },
      {
      id: 271,
      title: "Grab Carrer",
      category: "freelance",
      link: 'https://grab.careers/locations-indonesia/?ct=ID',
      img: "./src/asset-271.jpg",
      desc: `Grab Carrer/ Internship`,
    },
    {
      id: 272,
      title: "Apple Academy",
      category: "freelance",
      link: 'https://developeracademy.apps.binus.ac.id/',
      img: "./src/asset-272.jpg",
      desc: `Apple Academy/ Internship`,
    },
    {
      id: 273,
      title: "Tokopedia Academy",
      category: "course",
      link: 'https://academy.tokopedia.com/events',
      img: "./src/asset-273.jpg",
      desc: `Tokopedia Academy/ Internship`,
    },
    {
      id: 274,
      title: "UI Collection",
      category: "freelance",
      link: 'https://collectui.com',
      img: "./src/asset-274.jpg",
      desc: `UI Inspiration`,
    },
    {
      id: 275,
      title: "Free 3D icons",
      category: "icon",
      link: 'https://free3dicon.com',
      img: "./src/asset-275.jpg",
      desc: `Free 3D Icons`,
    },
        {
      id: 276,
      title: "GlassDoor",
      category: "freelance",
      link: 'https://www.glassdoor.com/index.htm',
      img: "./src/asset-276.jpg",
      desc: `Jobs Internship`,
    },
    {
      id: 277,
      title: "Bukalapak Carrer",
      category: "freelance",
      link: 'https://careers.bukalapak.com/jobs',
      img: "./src/asset-277.jpg",
      desc: `Jobs Internship`,
    },
    {
      id: 278,
      title: "Lapa Ninja",
      category: "illustration",
      link: 'https://www.lapa.ninja/blog/free-illustrations-library-for-your-project/',
      img: "./src/asset-278.jpg",
      desc: `Lots of free illustration`,
    },
    {
      id: 279,
      title: "dbb Telkom",
      category: "freelance",
      link: 'https://internship.ddbtelkom.id,
      img: "./src/asset-279.jpg",
      desc: `Program Internship PT. Telekomunikasi Indonesia Tbk Direktorat Digital Business (TELKOM DDB) memberikan kesempatan bagi mahasiswa/i untuk melakukan penelitian`,
    },
];

// get parent element
const sectionCenter = document.querySelector(".section-center");
const btnContainer = document.querySelector(".btn-container");
// display all items when page loads

window.addEventListener("DOMContentLoaded", function () {
  diplayMenuItems(menu);
  displayMenuButtons();
  dislaySearch();
});

// Menu
function diplayMenuItems(menuItems) {
  let displayMenu = menuItems.map(function (item) {
    // console.log(item);

    return `<!-- Single Content -->
    <div class="item-content">
    <!-- image -->
    <div class="photo-box">
        <img src=${item.img} alt=${item.title}>
    </div>
    <!-- box title and icon -->
    <div class="title-and-icon">
        <!-- text body -->
        <div class="title">
            <h1>${item.title}</h1>
            <p>${item.desc}</p>
        </div>
        <div class="icon">
            <a href=${item.link} target="_blank" rel="noopener"
            <button type="button" class="filter-btn" id="visit"
            >Visit</button>
            </a>
        </div>
    </div>
    </div>
    <!-- End Single Content -->` ;
  });
  displayMenu = displayMenu.join("");
  // console.log(displayMenu);

  sectionCenter.innerHTML = displayMenu;
}

// Button Category
function displayMenuButtons() {
  const categories = menu.reduce(
    function (values, item) {
      if (!values.includes(item.category)) {
        values.push(item.category);
      }
      return values;
    },
    ["all"]
  );
  
  const categoryBtns = categories
    .map(function (category) {
      return `<button type="button" class="filter-btn" data-id=${category}>
          ${category}
        </button>`;
    })
    .join("");

  btnContainer.innerHTML = categoryBtns;
  const filterBtns = btnContainer.querySelectorAll(".filter-btn");
  console.log(filterBtns);

  filterBtns.forEach(function (btn) {
    btn.addEventListener("click", function (e) {
      // console.log(e.currentTarget.dataset);
      const category = e.currentTarget.dataset.id;
      const menuCategory = menu.filter(function (menuItem) {
        // console.log(menuItem.category);
        if (menuItem.category === category) {
          return menuItem;
        }
      });
      if (category === "all") {
        diplayMenuItems(menu);
      } else {
        diplayMenuItems(menuCategory);
      }
    });
  });
}

//Search Bar
function dislaySearch(){
const searchBar = document.getElementById('searchBar');
searchBar.addEventListener('keyup',function(e){
  const searchString = e.target.value.toLowerCase();
  
  const searchFilter = menu.filter(function(displaySearch)  {
  return (
    displaySearch.title.toLowerCase().includes(searchString) ||
    displaySearch.desc.toLowerCase().includes(searchString)
  );
  });
  diplayMenuItems(searchFilter);
});
}